services:
  sku-check-web:
    build: .
    container_name: sku-check-web
    ports:
      - "5100:5100"
    volumes:
      - .:/app
      - /app/node_modules

    networks:
      - odoo19_odoo19-net

networks:
  odoo19_odoo19-net:
    external: true
