version: '3.8'

services:

  sku-check-web:
    build: .
    container_name: sku-check-web
    ports:
      - "5100:5100"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
